---
- name: RSYSLOG + Auditd + Bash Log Kurulumu (Ubuntu/Debian)
  hosts: all
  become: yes
  vars:
    bash_log_file: /var/log/bash.log
    remote_syslog_ip: "192.168.121.21"

  tasks:

    - name: Güncellemeleri al
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Auditd ve Audispd-plugins kurulumu
      apt:
        name:
          - auditd
          - audispd-plugins
        state: present

    - name: Rsyslog servisinin aktif ve çalışır olmasını sağla
      systemd:
        name: rsyslog
        enabled: yes
        state: started

    - name: Auditd servisinin aktif ve çalışır olmasını sağla
      systemd:
        name: auditd
        enabled: yes
        state: started

    - name: Bash log fonksiyonunu /etc/profile dosyasına ekle
      blockinfile:
        path: /etc/profile
        block: |
          # Bash Log
          PORT=$(who am i | awk '{print $5}' | tr -d '()')
          function history_to_syslog {
              local cmd=$(history 1 | awk '{$1=""; print substr($0,2)}')
              local p_dir=$(pwd)
              local LOG_NAME=$LOGNAME
              if [ "$cmd" != "$old_command" ]; then
                  logger -p local5.debug -- Bash SESSION=$$, from_remote_host=$PORT, USER=$LOG_NAME, PWD=$p_dir, CMD="$cmd"
              fi
              old_command=$cmd
          }
          trap history_to_syslog DEBUG
        marker: "# ANSIBLE-BASH-PROFILE-BEGIN"

    - name: Bash log fonksiyonunu /root/.bashrc dosyasına ekle
      blockinfile:
        path: /root/.bashrc
        block: |
          # Bash Log
          PORT=$(who am i | awk '{print $5}' | tr -d '()')
          function history_to_syslog {
              local cmd=$(history 1 | awk '{$1=""; print substr($0,2)}')
              local p_dir=$(pwd)
              local LOG_NAME=$LOGNAME
              if [ "$cmd" != "$old_command" ]; then
                  logger -p local5.debug -- Bash SESSION=$$, from_remote_host=$PORT, USER=$LOG_NAME, PWD=$p_dir, CMD="$cmd"
              fi
              old_command=$cmd
          }
          trap history_to_syslog DEBUG
        marker: "# ANSIBLE-BASH-RC-BEGIN"

    - name: Audit log pluginini aktif et
      lineinfile:
        path: /etc/audisp/plugins.d/syslog.conf
        regexp: '^active\s*='
        line: 'active = yes'
        backrefs: yes
      ignore_errors: yes

    - name: Rsyslog.conf üzerine audit log ayarını ekle
      blockinfile:
        path: /etc/rsyslog.conf
        block: |
          ############ RSYSLOG -> QRADAR ############
          {{ remote_syslog_ip }}
          # Audit log için
          $ModLoad imfile
          $InputFileName /var/log/audit/audit.log
          $InputFileTag tag_audit_log_$HOSTNAME:
          $InputFileStateFile audit_log
          $InputFileSeverity info
          $InputFileFacility local6
          $InputRunFileMonitor
        marker: "# ANSIBLE-RSYSLOG-AUDIT-BEGIN"
        insertafter: EOF

    - name: Bash log dosyasını oluştur
      file:
        path: "{{ bash_log_file }}"
        state: touch
        owner: root
        group: adm
        mode: '0640'

    - name: Rsyslog bash log config dosyasını oluştur
      copy:
        dest: /etc/rsyslog.d/bash.conf
        content: |
          # Bash log
          local5.debug {{ bash_log_file }}

    - name: 50-default.conf dosyasına kuralları ekle (varsa eklemez)
      blockinfile:
        path: /etc/rsyslog.d/50-default.conf
        block: |
          auth,authpriv.*                 /var/log/auth.log
          *.*;auth,authpriv.none          -/var/log/syslog
          cron.*                          /var/log/cron.log
          local1.*                        /var/log/sudo.log
          mail.err                         /var/log/mail.err
          *.emerg                          :omusrmsg:*
        marker: "# ANSIBLE-50-DEFAULT-CONF-BEGIN"
        insertafter: EOF

    - name: Rsyslog servisini yeniden başlat
      systemd:
        name: rsyslog
        state: restarted

    - name: Auditd servisini yeniden başlat
      systemd:
        name: auditd
        state: restarted
