---
- name: RSYSLOG + Auditd + Bash Log Kontrolü (Ubuntu/Debian)
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    bash_log_files:
      - /etc/profile
      - /root/.bashrc
    bash_log_code_snippet: "logger -p local5.debug"

  tasks:

  - name: Auditd servisinin kurulu olup olmadığını kontrol et
    ansible.builtin.shell: dpkg -l | grep auditd
    register: auditd_installed
    ignore_errors: yes

  - name: Auditd kontrol sonucu
    ansible.builtin.debug:
      msg: "{{ 'ok' if auditd_installed.rc == 0 else 'yok' }}"

  - name: Rsyslog servisinin kurulu olup olmadığını kontrol et
    ansible.builtin.shell: dpkg -l | grep rsyslog
    register: rsyslog_installed
    ignore_errors: yes

  - name: Rsyslog kontrol sonucu
    ansible.builtin.debug:
      msg: "{{ 'ok' if rsyslog_installed.rc == 0 else 'yok' }}"

  - name: Bash log kodunun /etc/profile ve /root/.bashrc dosyalarında olup olmadığını kontrol et
    ansible.builtin.shell: grep -q "{{ bash_log_code_snippet }}" {{ item }}
    register: bash_log_check
    ignore_errors: yes
    loop: "{{ bash_log_files }}"
    loop_control:
      label: "{{ item }}"

  - name: Bash log kontrol sonucu
    ansible.builtin.debug:
      msg: "{{ item.item }} : {{ 'ok' if item.rc == 0 else 'yok' }}"
    loop: "{{ bash_log_check.results }}"

  - name: Auditd syslog plugin aktif mi kontrol et
    ansible.builtin.shell: grep -E '^active\s*=\s*yes' /etc/audit/plugins.d/syslog.conf || grep -E '^active\s*=\s*yes' /etc/audisp/plugins.d/syslog.conf
    register: auditd_syslog_plugin
    ignore_errors: yes

  - name: Auditd syslog plugin kontrol sonucu
    ansible.builtin.debug:
      msg: "{{ 'ok' if auditd_syslog_plugin.rc == 0 else 'yok' }}"

  - name: Rsyslog bash log dosyası mevcut mu kontrol et
    ansible.builtin.stat:
      path: /var/log/bash.log
    register: bash_log_file

  - name: Bash log dosyası kontrol sonucu
    ansible.builtin.debug:
      msg: "{{ 'ok' if bash_log_file.stat.exists else 'yok' }}"

  - name: Rsyslog bash config dosyası mevcut mu kontrol et
    ansible.builtin.stat:
      path: /etc/rsyslog.d/bash.conf
    register: bash_conf_file

  - name: Bash conf dosyası kontrol sonucu
    ansible.builtin.debug:
      msg: "{{ 'ok' if bash_conf_file.stat.exists else 'yok' }}"

  - name: 50-default.conf dosyasının varlığı
    ansible.builtin.stat:
      path: /etc/rsyslog.d/50-default.conf
    register: rsyslog_default_conf

  - name: 50-default.conf kontrol sonucu
    ansible.builtin.debug:
      msg: "{{ 'ok' if rsyslog_default_conf.stat.exists else 'yok' }}"
