---
- name: RSYSLOG + Auditd + Bash Log Kontrolü (Sade)
  hosts: all
  become: yes

  vars:
    bash_log_entries:
      - '^PORT='
      - '^logger -p local5.debug'
      - '^function history_to_syslog'
      - '^declare cmd'
      - '^declare p_dir'
      - '^declare LOG_NAME'
      - '^cmd='
      - '^cmd=\$\(echo \$cmd'
      - '^p_dir='
      - '^LOG_NAME='
      - '^if \[ "\$cmd" != "\$old_command"'
      - '^logger -p local5.debug -- Bash'
      - '^fi$'
      - '^old_command='
      - '^\}$'
      - '^trap history_to_syslog DEBUG'

    rsyslog_lines:
      - '^\*.\* @@'
      - '^\$ModLoad imfile'
      - '^\$InputFileName /var/log/audit/audit.log'
      - '^\$InputFileTag tag_audit_log_.*'
      - '^\$InputFileStateFile audit_log'
      - '^\$InputFileSeverity info'
      - '^\$InputFileFacility local6'
      - '^\$InputRunFileMonitor'

    default_conf_lines:
      - '^auth,authpriv\.\*'
      - '^\*\.\*;auth,authpriv\.none'
      - '^cron\.\*'
      - '^local1\.\*'
      - '^mail\.err'
      - '^\*\.emerg'

  tasks:

    - name: Bash log satır kontrol (/etc/profile)
      shell: "grep -E '{{ item }}' /etc/profile"
      register: bash_profile_check
      ignore_errors: yes
      loop: "{{ bash_log_entries }}"
      loop_control:
        label: "{{ item }}"

    - name: Bash log satır kontrol (/root/.bashrc)
      shell: "grep -E '{{ item }}' /root/.bashrc"
      register: bash_bashrc_check
      ignore_errors: yes
      loop: "{{ bash_log_entries }}"
      loop_control:
        label: "{{ item }}"

    - name: Rsyslog.conf satır kontrol
      shell: "grep -E '{{ item }}' /etc/rsyslog.conf"
      register: rsyslog_conf_check
      ignore_errors: yes
      loop: "{{ rsyslog_lines }}"
      loop_control:
        label: "{{ item }}"

    - name: 50-default.conf satır kontrol
      shell: "grep -E '{{ item }}' /etc/rsyslog.d/50-default.conf"
      register: default_conf_check
      ignore_errors: yes
      loop: "{{ default_conf_lines }}"
      loop_control:
        label: "{{ item }}"

    - name: Sonuçları sade şekilde göster (VAR/YOK)
      debug:
        msg: |
          {% if item.rc == 0 %}
            {{ item.item }} : VAR
          {% else %}
            {{ item.item }} : YOK
          {% endif %}
      loop: 
        - "{{ bash_profile_check.results }}"
        - "{{ bash_bashrc_check.results }}"
        - "{{ rsyslog_conf_check.results }}"
        - "{{ default_conf_check.results }}"
