---
- name: RSYSLOG + Auditd + Bash Log Kurulumu (Ubuntu/Debian)
  hosts: all
  become: yes
  vars:
    remote_syslog_server: "192.168.121.21"

  tasks:
    # 1. Paket kurulumu
    - name: apt cache güncelle
      apt:
        update_cache: yes

    - name: auditd ve rsyslog kur
      apt:
        name:
          - auditd
          - rsyslog
        state: present

    # 2. Servisleri enable + start
    - name: auditd ve rsyslog aktif et
      systemd:
        name: "{{ item }}"
        enabled: yes
        state: started
      loop:
        - auditd
        - rsyslog

    # 3. Bash log kodu
    - name: Bash log kodunu tanımla
      set_fact:
        bash_log_code: |
          # Bash Log
          PORT=`who am i | awk '{ print $5 }' | sed 's/(//g' | sed 's/)//g'`
          logger -p local5.debug -t "Bash $LOGNAME $$" User $LOGNAME logged from $PORT
          function history_to_syslog {
            declare cmd
            declare p_dir
            declare LOG_NAME
            cmd=$(history 1)
            cmd=$(echo $cmd |awk '{print substr($0,length($1)+2)}')
            p_dir=$(pwd)
            LOG_NAME=$(echo $LOGNAME)
            if [ "$cmd" != "$old_command" ]; then
              logger -p local5.debug -- Bash SESSION=$$, USER=$LOG_NAME, PWD=$p_dir, CMD="${cmd}"
            fi
            old_command=$cmd
          }
          trap history_to_syslog DEBUG || EXIT

    - name: /etc/profile içine bash log ekle
      blockinfile:
        path: /etc/profile
        block: "{{ bash_log_code }}"
        marker: "# {mark} ANSIBLE BASH LOG"
        insertafter: EOF

    - name: /root/.bashrc içine bash log ekle
      blockinfile:
        path: /root/.bashrc
        block: "{{ bash_log_code }}"
        marker: "# {mark} ANSIBLE BASH LOG"
        insertafter: EOF

    # 4. Audit syslog aktif et
    - name: audit syslog config dosyalarını kontrol et
      stat:
        path: "{{ item }}"
      loop:
        - /etc/audisp/plugins.d/syslog.conf
        - /etc/audit/plugins.d/syslog.conf
      register: audit_syslog_files

    - name: active = yes yap
      lineinfile:
        path: "{{ item.item }}"
        regexp: '^active\s*='
        line: 'active = yes'
      when: item.stat.exists
      loop: "{{ audit_syslog_files.results }}"

    # 5. Rsyslog audit + remote config
    - name: rsyslog audit ve remote log config ekle
      blockinfile:
        path: /etc/rsyslog.d/90-audit-remote.conf
        create: yes
        block: |
          # Remote syslog
          *.* @@{{ remote_syslog_server }}

          # Audit log
          $ModLoad imfile
          $InputFileName /var/log/audit/audit.log
          $InputFileTag audit_log:
          $InputFileStateFile audit_log
          $InputFileSeverity info
          $InputFileFacility local6
          $InputRunFileMonitor
        marker: "# {mark} ANSIBLE AUDIT REMOTE"

    # 6. Bash log dosyası
    - name: bash log dosyasını oluştur
      file:
        path: /var/log/bash.log
        state: touch
        owner: root
        group: adm
        mode: '0640'

    - name: bash rsyslog config ekle
      blockinfile:
        path: /etc/rsyslog.d/bash.conf
        create: yes
        block: |
          local5.debug    /var/log/bash.log
        marker: "# {mark} ANSIBLE BASH RSYSLOG"

    # 7. 50-default.conf ayarları
    - name: 50-default.conf kurallarını ekle
      lineinfile:
        path: /etc/rsyslog.d/50-default.conf
        regexp: "{{ item.regex }}"
        line: "{{ item.line }}"
      loop:
        - { regex: '^auth,authpriv', line: 'auth,authpriv.*                 /var/log/auth.log' }
        - { regex: '^\*\.\*;auth,authpriv\.none', line: '*.*;auth,authpriv.none          -/var/log/syslog' }
        - { regex: '^cron\.\*', line: 'cron.*                          /var/log/cron.log' }
        - { regex: '^local1\.\*', line: 'local1.*                        /var/log/sudo.log' }
        - { regex: '^mail\.err', line: 'mail.err                        /var/log/mail.err' }
        - { regex: '^\*\.emerg', line: '*.emerg                         :omusrmsg:*' }

    # 8. Servis restart
    - name: rsyslog ve auditd restart
      systemd:
        name: "{{ item }}"
        state: restarted
      loop:
        - rsyslog
        - auditd
