---
- name: RSYSLOG + Auditd + Bash Log Kurulumu
  hosts: all
  become: yes
  vars:
    remote_syslog_server: "192.168.121.21"
    
  tasks:
    # 1. Paket kurulumları
    - name: Güncelleme ve paket kurulumu
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - auditd
        - rsyslog
      tags: installation

    # 2. Servisleri etkinleştirme ve başlatma
    - name: Servisleri etkinleştir ve başlat
      systemd:
        name: "{{ item }}"
        enabled: yes
        state: started
        daemon_reload: yes
      loop:
        - rsyslog
        - auditd
      tags: services

    # 3. Bash loglama kodlarını ekleme
    - name: Bash loglama kodlarını tanımla
      set_fact:
        bash_log_code: |
          # Bash Log
          PORT=`who am i | awk '{ print $5 }' | sed 's/(//g' | sed 's/)//g'`
          logger -p local5.debug -t "Bash $LOGNAME $$" User $LOGNAME logged from $PORT
          function history_to_syslog
          {
          declare cmd
          declare p_dir
          declare LOG_NAME
          cmd=$(history 1)
          cmd=$(echo $cmd |awk '{print substr($0,length($1)+2)}')
          p_dir=$(pwd)
          LOG_NAME=$(echo $LOGNAME)
          if [ "$cmd" != "$old_command" ]; then
          logger -p local5.debug -- Bash SESSION = $$, from_remote_host = $PORT, USER = $LOG_NAME, PWD = $p_dir, CMD = "${cmd}"
          fi
          old_command=$cmd
          }
          trap history_to_syslog DEBUG || EXIT

    # /etc/profile dosyasına Ansible marker'ı ile blok ekle
    - name: /etc/profile dosyasına bash loglama kodunu ekle
      blockinfile:
        path: /etc/profile
        block: "{{ bash_log_code }}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - BASH LOGGING"
        insertafter: EOF
      tags: bash_config

    # /root/.bashrc dosyasına Ansible marker'ı ile blok ekle
    - name: /root/.bashrc dosyasına bash loglama kodunu ekle
      blockinfile:
        path: /root/.bashrc
        block: "{{ bash_log_code }}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - BASH LOGGING"
        insertafter: EOF
      tags: bash_config

    # 4. Audit syslog konfigürasyonu
    # Hangi dosyanın olduğunu bul ve düzenle
    - name: Audit syslog config dosyasını bul
      stat:
        path: "{{ item }}"
      register: audit_config_files
      loop:
        - /etc/audisp/plugins.d/syslog.conf
        - /etc/audit/plugins.d/syslog.conf
      tags: audit_config

    - name: Audit syslog config dosyasını düzenle
      lineinfile:
        path: "{{ item.item }}"
        regexp: '^active\s*='
        line: 'active = yes'
        state: present
      when: item.stat.exists
      loop: "{{ audit_config_files.results }}"
      tags: audit_config

    # 5. Rsyslog konfigürasyonu
    # Rsyslog.conf dosyasına Ansible marker'ı ile blok ekle
    - name: Rsyslog.conf dosyasına uzak sunucu ve audit log konfigürasyonu ekle
      blockinfile:
        path: /etc/rsyslog.conf
        block: |
          ############  RSYSLOG  QRADAR
          {{ remote_syslog_server }}
          ########################## FOR AUDITD
          # audit log
          $ModLoad imfile
          $InputFileName /var/log/audit/audit.log
          $InputFileTag tag_audit_log_.$hostname:
          $InputFileStateFile audit_log
          $InputFileSeverity info
          $InputFileFacility local6
          $InputRunFileMonitor
        marker: "# {mark} ANSIBLE MANAGED BLOCK - REMOTE LOGGING AND AUDITD"
        insertafter: EOF
      tags: rsyslog_config

    # Bash log dosyasını oluştur
    - name: Bash log dosyasını oluştur
      file:
        path: /var/log/bash.log
        state: touch
        owner: root
        group: adm
        mode: '0640'
      tags: bash_log_file

    # Rsyslog bash config dosyasını oluştur (marker kullanmıyoruz, çünkü küçük bir dosya)
    - name: Rsyslog bash config dosyasını oluştur
      copy:
        dest: /etc/rsyslog.d/bash.conf
        content: |
          # Bash log
          local5.debug           /var/log/bash.log
        owner: root
        group: root
        mode: '0644'
      tags: rsyslog_config

    # 6. 50-default.conf dosyasına gerekli satırları ekle
    # Her satır için lineinfile kullanarak, satır yoksa ekleyeceğiz
    - name: 50-default.conf dosyasına gerekli satırları ekle
      lineinfile:
        path: /etc/rsyslog.d/50-default.conf
        regexp: "{{ item.regex }}"
        line: "{{ item.line }}"
        state: present
      with_items:
        - { regex: '^auth,authpriv\.\*\s*', line: 'auth,authpriv.*                 /var/log/auth.log' }
        - { regex: '^\*\.\*;auth,authpriv\.none\s*', line: '*.*;auth,authpriv.none          -/var/log/syslog' }
        - { regex: '^cron\.\*\s*', line: 'cron.*                          /var/log/cron.log' }
        - { regex: '^local1\.\*\s*', line: 'local1.*                        /var/log/sudo.log' }
        - { regex: '^mail\.err\s*', line: 'mail.err                        /var/log/mail.err' }
        - { regex: '^\*\.emerg\s*', line: '*.emerg                         :omusrmsg:*' }
      tags: rsyslog_default_conf

    # 7. Servisleri restart et
    - name: Servisleri restart et
      systemd:
        name: "{{ item }}"
        state: restarted
      loop:
        - rsyslog
        - auditd
      tags: restart_services

    # 8. Servis durumlarını kontrol et
    - name: Servis durumlarını kontrol et
      systemd:
        name: "{{ item }}"
      loop:
        - rsyslog
        - auditd
      register: service_status
      tags: verification

    - name: Servis durumlarını göster
      debug:
        msg: "{{ item.item }} servisi durumu: {{ item.state }}"
      loop: "{{ service_status.results }}"
      tags: verification
