---
- name: RSYSLOG + Auditd + Bash Logging Kurulumu
  hosts: all
  become: true

  handlers:
    - name: restart rsyslog
      systemd:
        name: rsyslog
        state: restarted

    - name: restart auditd
      systemd:
        name: auditd
        state: restarted

  tasks:

  #################################################
  # PAKET & SERVİS
  #################################################

  - name: Auditd paketini kur
    apt:
      name: auditd
      state: present
      update_cache: yes

  - name: Auditd servisini aktif et
    systemd:
      name: auditd
      enabled: true
      state: started

  - name: Rsyslog servisini aktif et
    systemd:
      name: rsyslog
      enabled: true
      state: started

  #################################################
  # BASH LOGGING
  #################################################

  - name: Bash log kodunu /etc/profile dosyasına ekle
    blockinfile:
      path: /etc/profile
      marker: "# {mark} ANSIBLE BASH LOG"
      block: |
        PORT=`who am i | awk '{ print $5 }' | sed 's/(//g' | sed 's/)//g'`
        logger -p local5.debug -t "Bash $LOGNAME $$" User $LOGNAME logged from $PORT

        function history_to_syslog {
          declare cmd
          declare p_dir
          declare LOG_NAME
          cmd=$(history 1)
          cmd=$(echo $cmd | awk '{print substr($0,length($1)+2)}')
          p_dir=$(pwd)
          LOG_NAME=$(echo $LOGNAME)
          if [ "$cmd" != "$old_command" ]; then
            logger -p local5.debug -- Bash SESSION=$$, FROM=$PORT, USER=$LOG_NAME, PWD=$p_dir, CMD="${cmd}"
          fi
          old_command=$cmd
        }
        trap history_to_syslog DEBUG || EXIT

  - name: Bash log kodunu /root/.bashrc dosyasına ekle
    blockinfile:
      path: /root/.bashrc
      marker: "# {mark} ANSIBLE BASH LOG"
      block: |
        PORT=`who am i | awk '{ print $5 }' | sed 's/(//g' | sed 's/)//g'`
        logger -p local5.debug -t "Bash $LOGNAME $$" User $LOGNAME logged from $PORT

        function history_to_syslog {
          declare cmd
          declare p_dir
          declare LOG_NAME
          cmd=$(history 1)
          cmd=$(echo $cmd | awk '{print substr($0,length($1)+2)}')
          p_dir=$(pwd)
          LOG_NAME=$(echo $LOGNAME)
          if [ "$cmd" != "$old_command" ]; then
            logger -p local5.debug -- Bash SESSION=$$, FROM=$PORT, USER=$LOG_NAME, PWD=$p_dir, CMD="${cmd}"
          fi
          old_command=$cmd
        }
        trap history_to_syslog DEBUG || EXIT

  #################################################
  # AUDITD SYSLOG PATH TESPİT
  #################################################

  - name: audisp syslog.conf kontrol et
    stat:
      path: /etc/audisp/plugins.d/syslog.conf
    register: audisp_syslog

  - name: audit syslog.conf kontrol et
    stat:
      path: /etc/audit/plugins.d/syslog.conf
    register: audit_syslog

  #################################################
  # AUDITD SYSLOG AKTİF ET
  #################################################

  - name: Audit syslog plugin aktif et (audisp path)
    lineinfile:
      path: /etc/audisp/plugins.d/syslog.conf
      regexp: '^active\s*='
      line: 'active = yes'
    when: audisp_syslog.stat.exists
    notify: restart auditd

  - name: Audit syslog plugin aktif et (audit path)
    lineinfile:
      path: /etc/audit/plugins.d/syslog.conf
      regexp: '^active\s*='
      line: 'active = yes'
    when: audit_syslog.stat.exists
    notify: restart auditd

  - name: Audit syslog plugin yoksa fail et
    fail:
      msg: "Audit syslog plugin conf bulunamadı!"
    when:
      - not audisp_syslog.stat.exists
      - not audit_syslog.stat.exists

  #################################################
  # RSYSLOG CONFIG
  #################################################

  - name: Rsyslog audit + remote forwarding ekle
    blockinfile:
      path: /etc/rsyslog.conf
      marker: "# {mark} ANSIBLE AUDIT FORWARD"
      block: |
        ############ RSYSLOG QRADAR
       192.168.121.21

        ########################## FOR AUDITD
        $ModLoad imfile
        $InputFileName /var/log/audit/audit.log
        $InputFileTag tag_audit_log_.$hostname:
        $InputFileStateFile audit_log
        $InputFileSeverity info
        $InputFileFacility local6
        $InputRunFileMonitor
    notify: restart rsyslog

  #################################################
  # BASH LOG DOSYASI
  #################################################

  - name: Bash log dosyasını oluştur
    file:
      path: /var/log/bash.log
      state: touch
      mode: '0640'

  - name: Bash rsyslog config dosyasını oluştur
    copy:
      dest: /etc/rsyslog.d/60-bash.conf
      content: |
        # Bash log
        local5.debug    /var/log/bash.log
    notify: restart rsyslog

  #################################################
  # DEFAULT LOG RULES (VENDOR DOKUNMADAN)
  #################################################

  - name: Custom default rsyslog rules ekle
    copy:
      dest: /etc/rsyslog.d/60-custom-default.conf
      content: |
        auth,authpriv.*                 /var/log/auth.log
        *.*;auth,authpriv.none          -/var/log/syslog
        cron.*                          /var/log/cron.log
        local1.*                        /var/log/sudo.log
        mail.err                        /var/log/mail.err
        *.emerg                         :omusrmsg:*
    notify: restart rsyslog
