---
- name: RSYSLOG + Auditd + Bash Log Kontrolü
  hosts: all
  become: yes

  vars:
    qradar_ip: "192.168.121.21"

    # Bash log kontrol için regex
    bash_log_entries:
      - regexp: '^PORT='
      - regexp: '^logger -p local5.debug'
      - regexp: '^function history_to_syslog'
      - regexp: '^declare cmd'
      - regexp: '^declare p_dir'
      - regexp: '^declare LOG_NAME'
      - regexp: '^cmd='
      - regexp: '^cmd=\$\(echo \$cmd'
      - regexp: '^p_dir='
      - regexp: '^LOG_NAME='
      - regexp: '^if \[ "\$cmd" != "\$old_command"'
      - regexp: '^logger -p local5.debug -- Bash'
      - regexp: '^fi$'
      - regexp: '^old_command='
      - regexp: '^\}$'
      - regexp: '^trap history_to_syslog DEBUG'

    # Rsyslog.conf kontrol için
    rsyslog_lines:
      - { line: "*.* @@{{ qradar_ip }}:514", regexp: '^\*.\* @@' }
      - { line: "$ModLoad imfile", regexp: '^\$ModLoad imfile' }
      - { line: "$InputFileName /var/log/audit/audit.log", regexp: '^\$InputFileName /var/log/audit/audit.log' }
      - { line: "$InputFileTag tag_audit_log_.*", regexp: '^\$InputFileTag tag_audit_log_.*' }
      - { line: "$InputFileStateFile audit_log", regexp: '^\$InputFileStateFile audit_log' }
      - { line: "$InputFileSeverity info", regexp: '^\$InputFileSeverity info' }
      - { line: "$InputFileFacility local6", regexp: '^\$InputFileFacility local6' }
      - { line: "$InputRunFileMonitor", regexp: '^\$InputRunFileMonitor' }

    # 50-default.conf kontrol için
    default_conf_lines:
      - { line: "auth,authpriv.*                 /var/log/auth.log", regexp: '^auth,authpriv\.\*' }
      - { line: "*.*;auth,authpriv.none          -/var/log/syslog", regexp: '^\*\.\*;auth,authpriv\.none' }
      - { line: "cron.*                          /var/log/cron.log", regexp: '^cron\.\*' }
      - { line: "local1.*                        /var/log/sudo.log", regexp: '^local1\.\*' }
      - { line: "mail.err                        /var/log/mail.err", regexp: '^mail\.err' }
      - { line: "*.emerg                         :omusrmsg:*", regexp: '^\*\.emerg' }

  tasks:

    - name: Bash log satırlarını kontrol et (/etc/profile)
      shell: "grep -E '{{ item.regexp }}' /etc/profile"
      register: bash_profile_check
      ignore_errors: yes
      changed_when: false
      loop: "{{ bash_log_entries }}"
      loop_control:
        label: "{{ item.regexp }}"

    - name: Bash log satırlarını kontrol et (/root/.bashrc)
      shell: "grep -E '{{ item.regexp }}' /root/.bashrc"
      register: bash_bashrc_check
      ignore_errors: yes
      changed_when: false
      loop: "{{ bash_log_entries }}"
      loop_control:
        label: "{{ item.regexp }}"

    - name: Eksik satırları göster (/etc/profile)
      debug:
        msg: "Eksik Bash log satırı (profile): {{ item.item.regexp }}"
      loop: "{{ bash_profile_check.results }}"
      when: item.rc != 0

    - name: Eksik satırları göster (/root/.bashrc)
      debug:
        msg: "Eksik Bash log satırı (bashrc): {{ item.item.regexp }}"
      loop: "{{ bash_bashrc_check.results }}"
      when: item.rc != 0

    - name: Rsyslog.conf eksik satırları kontrol et
      shell: "grep -E '{{ item.regexp }}' /etc/rsyslog.conf"
      register: rsyslog_conf_check
      ignore_errors: yes
      changed_when: false
      loop: "{{ rsyslog_lines }}"
      loop_control:
        label: "{{ item.regexp }}"

    - name: Eksik satırları göster (rsyslog.conf)
      debug:
        msg: "Eksik Rsyslog satırı: {{ item.item.regexp }}"
      loop: "{{ rsyslog_conf_check.results }}"
      when: item.rc != 0

    - name: 50-default.conf eksik satırları kontrol et
      shell: "grep -E '{{ item.regexp }}' /etc/rsyslog.d/50-default.conf"
      register: default_conf_check
      ignore_errors: yes
      changed_when: false
      loop: "{{ default_conf_lines }}"
      loop_control:
        label: "{{ item.regexp }}"

    - name: Eksik satırları göster (50-default.conf)
      debug:
        msg: "Eksik 50-default.conf satırı: {{ item.item.regexp }}"
      loop: "{{ default_conf_check.results }}"
      when: item.rc != 0
