- name: RSYSLOG + Auditd + Bash Log Kurulumu
  hosts: all
  become: yes

  vars:
    qradar_ip: "192.168.121.21"

    rsyslog_qradar_block: |
      ############ RSYSLOG QRADAR ############
      *.* @@{{ qradar_ip }}:514
      ########################## AUDITD
      $ModLoad imfile
      $InputFileName /var/log/audit/audit.log
      $InputFileTag tag_audit_log_.$hostname:
      $InputFileStateFile audit_log
      $InputFileSeverity info
      $InputFileFacility local6
      $InputRunFileMonitor

    bash_log_block: |
      PORT=`who am i | awk '{ print $5 }' | sed 's/(//g' | sed 's/)//g'`
      logger -p local5.debug -t "Bash $LOGNAME $$" User $LOGNAME logged from $PORT
      function history_to_syslog {
        declare cmd
        declare p_dir
        declare LOG_NAME
        cmd=$(history 1)
        cmd=$(echo $cmd |awk '{print substr($0,length($1)+2)}')
        p_dir=$(pwd)
        LOG_NAME=$(echo $LOGNAME)
        if [ "$cmd" != "$old_command" ]; then
          logger -p local5.debug -- Bash SESSION=$$, USER=$LOG_NAME, PWD=$p_dir, CMD="${cmd}"
        fi
        old_command=$cmd
      }
      trap history_to_syslog DEBUG || EXIT

  tasks:

    - name: Auditd kurulumu
      apt:
        name: auditd
        state: present
        update_cache: yes

    - name: Auditd servisini aktif et
      service:
        name: auditd
        state: started
        enabled: yes

    - name: Rsyslog servisini aktif et
      service:
        name: rsyslog
        state: started
        enabled: yes

    - name: Audit syslog plugin aktif et
      lineinfile:
        path: /etc/audit/plugins.d/syslog.conf
        regexp: '^active\s*='
        line: 'active = yes'
        create: yes

    - name: /etc/profile bash log script var mı kontrol et
      shell: grep -q "history_to_syslog" /etc/profile
      register: profile_bashlog
      failed_when: false
      changed_when: false

    - name: /etc/profile bash log script ekle (yoksa)
      blockinfile:
        path: /etc/profile
        insertafter: EOF
        block: "{{ bash_log_block }}"
      when: profile_bashlog.rc != 0

    - name: /root/.bashrc bash log script var mı kontrol et
      shell: grep -q "history_to_syslog" /root/.bashrc
      register: bashrc_bashlog
      failed_when: false
      changed_when: false

    - name: /root/.bashrc bash log script ekle (yoksa)
      blockinfile:
        path: /root/.bashrc
        insertafter: EOF
        block: "{{ bash_log_block }}"
      when: bashrc_bashlog.rc != 0

    - name: Bash log dosyası oluştur (yoksa)
      file:
        path: /var/log/bash.log
        state: file
        owner: root
        group: adm
        mode: '0640'

    - name: Bash rsyslog satırı var mı kontrol et
      shell: grep -Fq "local5.debug    /var/log/bash.log" /etc/rsyslog.d/bash.conf
      register: bashrsyslog_exists
      failed_when: false
      changed_when: false

    - name: Bash rsyslog satırı ekle (yoksa)
      lineinfile:
        path: /etc/rsyslog.d/bash.conf
        line: "local5.debug    /var/log/bash.log"
        create: yes
      when: bashrsyslog_exists.rc != 0
      notify: restart rsyslog

    - name: Rsyslog.conf içine QRadar + Auditd kurallarını ekle
      blockinfile:
        path: /etc/rsyslog.conf
        marker: "# {mark} ANSIBLE_QRADAR_AUDITD"
        insertafter: EOF
        block: "{{ rsyslog_qradar_block }}"
      notify: restart rsyslog

  handlers:
    - name: restart rsyslog
      service:
        name: rsyslog
        state: restarted
