- name: RSYSLOG + Auditd + Bash Log Kurulumu
  hosts: all
  become: yes

  vars:
    qradar_ip: "192.168.121.21"

    rsyslog_qradar_block: |
      ############  RSYSLOG  QRADAR ############

      # Remote log server
      *.* @@{{ qradar_ip }}:514

      ########################## FOR AUDITD
      # audit log
      $ModLoad imfile
      $InputFileName /var/log/audit/audit.log
      $InputFileTag tag_audit_log_.$hostname:
      $InputFileStateFile audit_log
      $InputFileSeverity info
      $InputFileFacility local6
      $InputRunFileMonitor

    bash_log_block: |
      # Bash Log
      PORT=`who am i | awk '{ print $5 }' | sed 's/(//g' | sed 's/)//g'`
      logger -p local5.debug -t "Bash $LOGNAME $$" User $LOGNAME logged from $PORT
      function history_to_syslog
      {
      declare cmd
      declare p_dir
      declare LOG_NAME
      cmd=$(history 1)
      cmd=$(echo $cmd |awk '{print substr($0,length($1)+2)}')
      p_dir=$(pwd)
      LOG_NAME=$(echo $LOGNAME)
      if [ "$cmd" != "$old_command" ]; then
      logger -p local5.debug -- Bash SESSION = $$, from_remote_host = $PORT, USER = $LOG_NAME, PWD = $p_dir, CMD = "${cmd}"
      fi
      old_command=$cmd
      }
      trap history_to_syslog DEBUG || EXIT

  tasks:

    - name: Auditd kurulumu
      apt:
        name: auditd
        state: present
        update_cache: yes

    - name: Auditd servisini aktif et
      service:
        name: auditd
        state: started
        enabled: yes

    - name: Rsyslog servisini aktif et
      service:
        name: rsyslog
        state: started
        enabled: yes

    - name: Audit log syslog plugin aktif et
      lineinfile:
        path: /etc/audit/plugins.d/syslog.conf
        regexp: '^active\s*='
        line: 'active = yes'
        create: yes

    - name: Bash log kodlarını /etc/profile içine ekle
      blockinfile:
        path: /etc/profile
        marker: "# {mark} ANSIBLE_BASH_LOG"
        insertafter: EOF
        block: "{{ bash_log_block }}"

    - name: Bash log kodlarını /root/.bashrc içine ekle
      blockinfile:
        path: /root/.bashrc
        marker: "# {mark} ANSIBLE_BASH_LOG"
        insertafter: EOF
        block: "{{ bash_log_block }}"

    - name: Bash log dosyası var mı kontrol et
      stat:
        path: /var/log/bash.log
      register: bash_log_stat

    - name: Bash log dosyasını oluştur (SADECE YOKSA)
      file:
        path: /var/log/bash.log
        state: file
        owner: root
        group: adm
        mode: '0640'
      when: not bash_log_stat.stat.exists

    - name: Rsyslog bash konfigürasyonu ekle
      copy:
        dest: /etc/rsyslog.d/bash.conf
        content: |
          # Bash log
          local5.debug           /var/log/bash.log
        owner: root
        group: root
        mode: '0644'

    - name: Rsyslog.conf içine QRadar + Auditd kurallarını ekle
      blockinfile:
        path: /etc/rsyslog.conf
        marker: "# {mark} ANSIBLE_QRADAR_AUDITD"
        insertafter: EOF
        block: "{{ rsyslog_qradar_block }}"

    - name: Rsyslog yeniden başlat
      service:
        name: rsyslog
        state: restarted

    - name: Auditd yeniden başlat
      service:
        name: auditd
        state: restarted
