---
- name: RSYSLOG + Auditd + Bash Log Kontrolü
  hosts: all
  become: yes

  vars:
    bash_log_entries:
      - regexp: '^PORT='
      - regexp: '^logger -p local5.debug'
      - regexp: '^function history_to_syslog'
      - regexp: '^declare cmd'
      - regexp: '^declare p_dir'
      - regexp: '^declare LOG_NAME'
      - regexp: '^cmd='
      - regexp: '^cmd=\$\(echo \$cmd'
      - regexp: '^p_dir='
      - regexp: '^LOG_NAME='
      - regexp: '^if \[ "\$cmd" != "\$old_command"'
      - regexp: '^logger -p local5.debug -- Bash'
      - regexp: '^fi$'
      - regexp: '^old_command='
      - regexp: '^\}$'
      - regexp: '^trap history_to_syslog DEBUG'

    rsyslog_lines:
      - regexp: '^\*.\* @@192\.168\.121\.21:514'
      - regexp: '^\$ModLoad imfile'
      - regexp: '^\$InputFileName /var/log/audit/audit.log'
      - regexp: '^\$InputFileTag tag_audit_log_.*'
      - regexp: '^\$InputFileStateFile audit_log'
      - regexp: '^\$InputFileSeverity info'
      - regexp: '^\$InputFileFacility local6'
      - regexp: '^\$InputRunFileMonitor'

    default_conf_lines:
      - regexp: '^auth,authpriv\.\*'
      - regexp: '^\*\.\*;auth,authpriv\.none'
      - regexp: '^cron\.\*'
      - regexp: '^local1\.\*'
      - regexp: '^mail\.err'
      - regexp: '^\*\.emerg'

  tasks:

    - name: Bash log satırlarını kontrol et (/etc/profile)
      shell: "grep -E '{{ item.regexp }}' /etc/profile"
      register: bash_profile_check
      ignore_errors: yes
      loop: "{{ bash_log_entries }}"
      loop_control:
        label: "{{ item.regexp }}"

    - name: Bash log satırlarını kontrol et (/root/.bashrc)
      shell: "grep -E '{{ item.regexp }}' /root/.bashrc"
      register: bash_bashrc_check
      ignore_errors: yes
      loop: "{{ bash_log_entries }}"
      loop_control:
        label: "{{ item.regexp }}"

    - name: Rsyslog satırlarını kontrol et (/etc/rsyslog.conf)
      shell: "grep -E '{{ item.regexp }}' /etc/rsyslog.conf"
      register: rsyslog_check
      ignore_errors: yes
      loop: "{{ rsyslog_lines }}"
      loop_control:
        label: "{{ item.regexp }}"

    - name: 50-default.conf satırlarını kontrol et (/etc/rsyslog.d/50-default.conf)
      shell: "grep -E '{{ item.regexp }}' /etc/rsyslog.d/50-default.conf"
      register: default_conf_check
      ignore_errors: yes
      loop: "{{ default_conf_lines }}"
      loop_control:
        label: "{{ item.regexp }}"

    - name: Sonuçları göster (/etc/profile)
      debug:
        msg: "Eksik Bash log satırı (profile): {{ item.item.regexp }}"
      loop: "{{ bash_profile_check.results }}"
      when: item.rc != 0

    - name: Sonuçları göster (/root/.bashrc)
      debug:
        msg: "Eksik Bash log satırı (bashrc): {{ item.item.regexp }}"
      loop: "{{ bash_bashrc_check.results }}"
      when: item.rc != 0

    - name: Sonuçları göster (/etc/rsyslog.conf)
      debug:
        msg: "Eksik Rsyslog satırı: {{ item.item.regexp }}"
      loop: "{{ rsyslog_check.results }}"
      when: item.rc != 0

    - name: Sonuçları göster (50-default.conf)
      debug:
        msg: "Eksik 50-default.conf satırı: {{ item.item.regexp }}"
      loop: "{{ default_conf_check.results }}"
      when: item.rc != 0
