---
- name: RSYSLOG + Auditd + Bash Log Kurulumu (Ubuntu/Debian)
  hosts: all
  become: yes
  vars:
    bash_log_file: /var/log/bash.log
    remote_syslog_ip: "192.168.121.21"

  tasks:

    # --------------------------
    # 1️⃣ Paket Kurulumu
    # --------------------------
    - name: Auditd ve Audispd-plugins kurulumu (varsa atla)
      apt:
        name:
          - auditd
          - audispd-plugins
        state: present
        update_cache: yes

    # --------------------------
    # 2️⃣ Servisler
    # --------------------------
    - name: Rsyslog servisinin aktif ve çalışır olmasını sağla
      systemd:
        name: rsyslog
        enabled: yes
        state: started

    - name: Auditd servisinin aktif ve çalışır olmasını sağla
      systemd:
        name: auditd
        enabled: yes
        state: started

    # --------------------------
    # 3️⃣ Bash log fonksiyonu
    # --------------------------
    - name: Bash log fonksiyonunu /etc/profile dosyasına ekle (varsa atla)
      blockinfile:
        path: /etc/profile
        block: |
          # Bash Log
          PORT=$(who am i | awk '{print $5}' | tr -d '()')
          function history_to_syslog {
              local cmd=$(history 1 | awk '{$1=""; print substr($0,2)}')
              local p_dir=$(pwd)
              local LOG_NAME=$LOGNAME
              if [ "$cmd" != "$old_command" ]; then
                  logger -p local5.debug -- Bash SESSION=$$, from_remote_host=$PORT, USER=$LOG_NAME, PWD=$p_dir, CMD="$cmd"
              fi
              old_command=$cmd
          }
          trap history_to_syslog DEBUG
        marker: "# ANSIBLE-BASH-PROFILE-BEGIN"

    - name: Bash log fonksiyonunu /root/.bashrc dosyasına ekle (varsa atla)
      blockinfile:
        path: /root/.bashrc
        block: |
          # Bash Log
          PORT=$(who am i | awk '{print $5}' | tr -d '()')
          function history_to_syslog {
              local cmd=$(history 1 | awk '{$1=""; print substr($0,2)}')
              local p_dir=$(pwd)
              local LOG_NAME=$LOGNAME
              if [ "$cmd" != "$old_command" ]; then
                  logger -p local5.debug -- Bash SESSION=$$, from_remote_host=$PORT, USER=$LOG_NAME, PWD=$p_dir, CMD="$cmd"
              fi
              old_command=$cmd
          }
          trap history_to_syslog DEBUG
        marker: "# ANSIBLE-BASH-RC-BEGIN"

    # --------------------------
    # 4️⃣ Audit plugin aktif et
    # --------------------------
    - name: Audit log pluginini aktif et (varsa atla)
      lineinfile:
        path: /etc/audisp/plugins.d/syslog.conf
        regexp: '^active\s*='
        line: 'active = yes'
        backrefs: yes
      ignore_errors: yes

    # --------------------------
    # 5️⃣ Rsyslog.conf audit log ekle
    # --------------------------
    - name: Rsyslog.conf üzerine audit log ayarını ekle (varsa atla)
      blockinfile:
        path: /etc/rsyslog.conf
        block: |
          # BEGIN RSYSLOG QRADAR + AUDIT
          ############  RSYSLOG  QRADAR
          {{ remote_syslog_ip }}

          ########################## FOR AUDITD
          # audit log
          $ModLoad imfile
          $InputFileName /var/log/audit/audit.log
          $InputFileTag tag_audit_log_$HOSTNAME:
          $InputFileStateFile audit_log
          $InputFileSeverity info
          $InputFileFacility local6
          $InputRunFileMonitor
          # END RSYSLOG QRADAR + AUDIT
        marker: "# ANSIBLE-RSYSLOG-AUDIT-BEGIN"
        insertafter: EOF

    # --------------------------
    # 6️⃣ Bash log dosyası
    # --------------------------
    - name: Bash log dosyasını oluştur (varsa atla)
      file:
        path: "{{ bash_log_file }}"
        state: touch
        owner: root
        group: adm
        mode: '0640'

    # --------------------------
    # 7️⃣ Rsyslog bash log config
    # --------------------------
    - name: Rsyslog bash log config dosyasını oluştur (varsa atla)
      copy:
        dest: /etc/rsyslog.d/bash.conf
        content: |
          # Bash log
          local5.debug {{ bash_log_file }}
        force: no

    # --------------------------
    # 8️⃣ 50-default.conf güncelle
    # --------------------------
    - name: 50-default.conf dosyasına kuralları ekle sadece eksikse
      blockinfile:
        path: /etc/rsyslog.d/50-default.conf
        block: |
          auth,authpriv.*                 /var/log/auth.log
          *.*;auth,authpriv.none          -/var/log/syslog
          cron.*                          /var/log/cron.log
          local1.*                        /var/log/sudo.log
          mail.err                         /var/log/mail.err
          *.emerg                          :omusrmsg:*
        marker: "# ANSIBLE-50-DEFAULT-CONF-BEGIN"
        insertafter: EOF

    # --------------------------
    # 9️⃣ Servisleri yeniden başlat
    # --------------------------
    - name: Rsyslog servisini yeniden başlat (varsa değişiklik yoksa atla)
      systemd:
        name: rsyslog
        state: restarted

    - name: Auditd servisini yeniden başlat (varsa değişiklik yoksa atla)
      systemd:
        name: auditd
        state: restarted
